apiVersion: apps/v1
kind: Deployment
metadata:
    name: olivetin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olivetin
  template:
    metadata:
      labels:
        app: olivetin
    spec:
      containers:
        - name: olivetin
          image: docker.io/jamesread/olivetin:latest
          ports:
            - containerPort: {{ .Values.ingress.servicePort }}
          volumeMounts:
            - name: olivetin-config
              mountPath: "/config"
              readOnly: true
            {{- if or (.Values.ssh.existingSecret) (.Values.ssh.id_rsa) }}
            - name: olivetin-ssh-secret
              mountPath: "/home/olivetin/.ssh/id_rsa"
              subPath: "id_rsa"
              readOnly: true
            {{- end }}       
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:{{ .Values.ingress.servicePort }}
            initialDelaySeconds: 5
            periodSeconds: 30
      volumes:
        - name: olivetin-config
          configMap:
            name: olivetin-config
        {{- if .Values.ssh.existingSecret }}
        - name: olivetin-ssh-secret
          secret:
            secretName: {{ .Values.ssh.existingSecret }}
        {{- else if .Values.ssh.id_rsa }}
        - name: olivetin-ssh-secret
          secret:
            secretName: olivetin-ssh-secret
        {{- end }}

